<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PRI - Registration for project defenses has been opened</title>
</head>
<body>
<div style="margin-top: 10px">Dear Mr./Ms. ${user}</div>
<div>Registration for project defenses has been opened. Please sign up for a free date in the system.</div>
<br/>
<div> Yours sincerely,</div>
<div> Subject Coordinator</div>
</body>
</html>